### ISSUE TITLE
Type Annotations?

### ISSUE THREAD

**Issue by ThomasThelen** [WeileiZeng/tutorial#17]
I was thumbing through your Python code (I just started Nielsen and Chuang so I'm after your QEC stuff) and noticed that it might be a good idea to show type annotations at some point. Of course, [not everything](https://stackoverflow.com/questions/57409867/should-i-annotate-types-everywhere) needs it but can be useful for beginners to help keep track of things!

**Comment by WeileiZeng** [comment]
Sounds good. I should start doing that. I studied python 8 years ago with python 2.6, without annotations, and just use it since then.
I will incorporate it in my next updating version (not sure when it is).

I am also a bit behind the QEC tutorial, hopefully get an update next quarter! 

Sounds very cool bro. I am in Riverside, and hope get a chance to visit google quantum or MS Q-station or UCSB sometime.

**Comment by ThomasThelen** [comment]
No rush! I'm trying to get better at them myself. If you ever make it up to UCSB, shoot me an email!
